
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - "tmp/**/*"
    - "gemfiles/*"

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

inherit_mode:
  merge:
    - Exclude