name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup system deps
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
    - name: Test
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rubocop
